[features]
seeds = false
skip-lint = false
[programs.localnet]
profile_picture = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sandhilt/.config/solana/id.json"

[scripts]
test = "npx jest --preset ts-jest"
